/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonToIndex: typeof import('./components/button-to-index.vue')['default']
    Chart: typeof import('./components/chart.vue')['default']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/line-chart.vue')['default']
    PageHeader: typeof import('./components/page-header.vue')['default']
    PageHeaderNav: typeof import('./components/page-header-nav.vue')['default']
    PageHeaderTitle: typeof import('./components/page-header-title.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggler: typeof import('./components/theme-toggler.vue')['default']
  }
}
