# 项目相关配置
iahms:
  # 名称(全名：Iuvenis Aquilae Hotel Management System)
  name: Iahms
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2024
  # 文件路径
  profile: /home/iahms/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math：数字计算 char：字符验证
  captchaType: math

# 开发环境配置
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    # tomcat 的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数
    accept-count: 1000
    threads:
      # tomcat最大线程数(默认200)
      max: 800
      # tomcat启动初始化的线程数(默认10)
      min-spare: 100

# Spring配置
spring:
#  redis:
#    host: 192.168.101.100
#    port: 6379
#    database: 0
#    timeout: 5000ms
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 5
#        min-idle: 2
  cache:
    # 指定缓存类型 jcache 本地缓存 redis 缓存
    type: redis
    redis:
      # 缓存过期时间（ms）
      time-to-live: 86400000  # 86400000 = 1天
      # 指定前缀
      use-key-prefix: true
      # 是否缓存空值，可以防止缓存穿透
      cache-null-values: true
  mvc:
    pathmatch:
      # 路径匹配策略
      matching-strategy: ANT_PATH_MATCHER
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: druid,mybatis
  output:
    ansi:
      # 总是启用彩色日志
      enabled: always

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
  ip:
    maxRetryCount: 15
    lockTime: 15

# 令牌配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
  # 令牌有效时间（默认30分钟）
  expireTime: 30

# swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# redis详细日志
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG